---
# tasks file for tomcat_role
- name: Add the OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
- include_tasks: "{{ ansible_os_family }}.yml"

#- name: gather os specific variables
#  include_vars: "{{ item }}"
#  with_first_found:
#    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
#    - "{{ ansible_os_family }}.yml"
#  tags: vars
#- include_tasks: RedHat.yml
#  when: ansible_os_family == "RedHat"

#- include_tasks: Debian.yml
#  when: ansible_os_family == "Debian"
